"""Initial migration

Revision ID: 03d8391921ae
Revises:
Create Date: 2020-08-04 21:59:30.890793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03d8391921ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_link',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('organization', sa.String(length=80), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('shortpath', sa.String(length=200), nullable=False),
    sa.Column('shortpath_prefix', sa.String(length=200), nullable=False),
    sa.Column('destination_url', sa.String(length=3000), nullable=False),
    sa.Column('visits_count', sa.Integer(), nullable=True),
    sa.Column('visits_count_last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_link_shortpath'), 'short_link', ['shortpath'], unique=False)
    op.create_index(op.f('ix_short_link_shortpath_prefix'), 'short_link', ['shortpath_prefix'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('organization', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('accepted_terms_at', sa.DateTime(), nullable=True),
    sa.Column('domain_type', sa.String(length=30), nullable=True),
    sa.Column('notifications', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_short_link_shortpath_prefix'), table_name='short_link')
    op.drop_index(op.f('ix_short_link_shortpath'), table_name='short_link')
    op.drop_table('short_link')
    # ### end Alembic commands ###
