"""Add lookup key

Revision ID: 11880ac0ca4a
Revises: 03d8391921ae
Create Date: 2020-08-05 22:52:17.165548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11880ac0ca4a'
down_revision = '03d8391921ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_link', sa.Column('key', sa.String(length=500), nullable=False))
    op.create_index(op.f('ix_short_link_key'), 'short_link', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_link_key'), table_name='short_link')
    op.drop_column('short_link', 'key')
    # ### end Alembic commands ###
