"""Add unlisted column

Revision ID: 468d3670d340
Revises: b346dcd75c14
Create Date: 2023-08-29 21:13:34.313599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468d3670d340'
down_revision = 'b346dcd75c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_link', sa.Column('unlisted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_link', 'unlisted')
    # ### end Alembic commands ###
