"""Add type column

Revision ID: 7f9e28ceb511
Revises: c7b70ea13df9
Create Date: 2021-02-19 12:04:22.508503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9e28ceb511'
down_revision = 'c7b70ea13df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_link', sa.Column('type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_link', 'type')
    # ### end Alembic commands ###
