"""Add enabled user property

Revision ID: b9dcddc9a697
Revises: 11880ac0ca4a
Create Date: 2021-02-01 08:55:50.545905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dcddc9a697'
down_revision = '11880ac0ca4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enabled')
    # ### end Alembic commands ###
